[package]
name = "locdev"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["cargo", "derive"] }
colored = "2.0.0"
tokio = { version = "1.28.1", features = ["full"] }
